### ISSUE TITLE
permute messages via shuffle

### ISSUE THREAD

**Issue by goozang-records** [4meta5/wordplay#1]
and exhaustively deshuffle messages to find all legible sentences

* start with algorithms for generating all permutations for a given word and checking if the permutation is a valid word
* provide functionality for shuffling a message using permutation algorithm (encrypt and aspire for providing decrypt info in the form of how to apply inv steps to get original message)

**Comment by libreamartists** [comment]
this issue deserves to be its own library, using https://github.com/4meta5/forty40
